= Northern Lights Copyright Information
:revdate: February 20, 2024

Copyright (C) 2024 George Witt

All rights reserved.

*This software is provided by the copyright holders and contributors "as is" and
any express or implied warranties, including, but not limited to, the implied
warranties of merchantability and fitness for a particular purpose are
disclaimed. In no event shall the copyright holders or contributors be liable
for any direct, indirect, incidental, special, exemplary, or consequential
damages (including, but not limited to, procurement of substitute goods or
services; loss of use, data, orprofits; or business interruption) however caused
and on any theory of liability, whether in contract, strict liability, or tort
(including negligence or otherwise) arising in any way out of the use of this
software, even if advised of the possibility of such damage.*

The views and conclusions contained in the software and documentation are those
of the contributors and should not be interpreted as representing official
policies, either expressed or implied, of the Northern Lights Project.

== Attribution Notices
All required license text from imported code is included in link:LICENSES[LICENSES].
The following is a list of copyright notices from imported code.

=== libfdt

Copyright (C) 2006 David Gibson, IBM Corporation. +
Copyright (C) 2012 David Gibson, IBM Corporation. +
Copyright (C) 2012 Kim Phillips, Freescale Semiconductor. +
Copyright (C) 2014 David Gibson <david@gibson.dropbear.id.au> +
Copyright (C) 2016 Free Electrons +
Copyright (C) 2016 NextThing Co. +
Copyright (C) 2018 embedded brains GmbH
