= Northern Lights Copyright Information
:revdate: February 20, 2024

Copyright (C) 2024 George Witt

All rights reserved.

*This software is provided "as is" and the author disclaims all warranties with
regard to this software including all implied warranties of merchantability and
fitness. In no event shall the author be liable for any special, direct,
indirect, or consequential damages or any damages whatsoever resulting from loss
of use, data or profits, whether in an action of contract, negligence or other
tortious action, arising out of or in connection with the use or performance of
this software, even if advised of the possibility of such damages.*

== Attribution Notices
All required license text from imported code is included in link:LICENSES[LICENSES].
The following is a list of copyright notices from imported code.

=== libfdt

Copyright (C) 2006 David Gibson, IBM Corporation. +
Copyright (C) 2012 David Gibson, IBM Corporation. +
Copyright (C) 2012 Kim Phillips, Freescale Semiconductor. +
Copyright (C) 2014 David Gibson <david@gibson.dropbear.id.au> +
Copyright (C) 2016 Free Electrons +
Copyright (C) 2016 NextThing Co. +
Copyright (C) 2018 embedded brains GmbH
