= Northern Lights

A secure and reliable operating system

Copyright (C) 2024 George Witt. All rights reserved.

[IMPORTANT]
====
This is *not* free software. There author reserves certain copyrights and patent
rights which disqualify this software from being considered free and/or open
source software under the FSF and OSI definitions. Please see
link:COPYING.adoc[COPYING] for more information.
====

The Northern Lights kernel and its operating system components are
"source-available" software. You are free to use this software internally for
non-commercial purposes, but modification and distribution is not allowed
(other than to the minimal extent required to comply with platform terms). In
the future, it will be released under a free software license. Refer to
link:COPYING.adoc[COPYING] for license terms and required notices.

Contributions are not accepted at this time, however bug reports are welcome.

This program is provided to anyone in the hope that it will be useful, but
*without any warranty*, not even the implied warranty of *merchantability* or
*fitness for a particular purpose*.

== Build Instructions
This OS is designed to be cross-compiled. To build the debug version for the
RISC-V architecture, you need to install the `riscv-gnu-toolchain` to
`/opt/riscv` with LLVM and Ada enabled. After doing that, simply run:

$ `ARCH=riscv SKU=debug ./configure && make`

Other architectures are not currently supported.

== Booting

This OS currently runs on the QEMU virt platform. Simply add the
`-kernel boot/kernimg` flag to QEMU's arguments.

link:https://nltsproject.org[nltsproject.org]
